

DROP TABLE MakeDim
DROP TABLE DimAppList

/* Create temp tables */
CREATE TABLE MakeDim ( ServerName VARCHAR(50), AppName VARCHAR(1000))

CREATE TABLE DimAppList(ServerName VARCHAR(50), AppName VARCHAR(5000))

/* Insert Data */
insert into MakeDim values('AFSDEPOT','AFS')
insert into MakeDim values('AFSDEPOT','MIS')
insert into MakeDim values('AFSDEPOT','Shared SQL Server')
insert into MakeDim values('AFSICS03','AFS')
insert into MakeDim values('AFSICS03','Image Quality Monitor')
insert into MakeDim values('AFSICS03','VisionIP')
insert into MakeDim values('AFSIRD01','IRD')
insert into MakeDim values('AFSRIMAGE2','AFS')
insert into MakeDim values('AFSRIMAGE2','Rimage')
insert into MakeDim values('AFSRIMAGE2','VisionIP')
insert into MakeDim values('AFSSCU03','AFS')
insert into MakeDim values('AFSSCU03','CAPI')
insert into MakeDim values('AFSSCU03','Unisort')
insert into MakeDim values('AFSSCU03','VisionIP')
insert into MakeDim values('AFSTSTAPP01','MDS')
insert into MakeDim values('AFSTSTDPT02','AFS')
insert into MakeDim values('AFSTSTIRD01','AFS')
insert into MakeDim values('AFSTSTSQL01','AFS')
insert into MakeDim values('AFSTSTVSU02','AFS')
insert into MakeDim values('AFSVSU','AFS/VisionIP/Frodo/VSU')
insert into MakeDim values('AFSXVISION01','AFS')
insert into MakeDim values('AFSXVISION01','VisionIP')
insert into MakeDim values('AFSXVISION01','xVision')
insert into MakeDim values('AFSXVISION02','AFS')
insert into MakeDim values('AFSXVISION02','VisionIP')
insert into MakeDim values('AFSXVISION02','xVision')
insert into MakeDim values('AFSXVISIONTST01','AFS')
insert into MakeDim values('AFSXVISIONTST02','AFS')
insert into MakeDim values('CAG','Bloomberg')
insert into MakeDim values('CCTAPP01','Condo Certs')
insert into MakeDim values('CCTAPP02','Condo Certs')
insert into MakeDim values('DEVAPP09','Taskflow (Image Exceptions)')
insert into MakeDim values('DEVSKL02','Shared SQL Server')
insert into MakeDim values('DEVSPSCC2-6','Condo Certs')
insert into MakeDim values('DEVSQL01','SQL')
insert into MakeDim values('DEVSQL03','SQL')
insert into MakeDim values('EMPAPP01','Business Objects')
insert into MakeDim values('FIRAPP03','ImageExceptions')
insert into MakeDim values('FIRAPPTST','CAB')
insert into MakeDim values('FIRIISTST','CAB')
insert into MakeDim values('FIRNET03','CABanc')
insert into MakeDim values('FIRNET03','VMS')
insert into MakeDim values('FIRNET04.condocerts.dmz','Condo Certs')
insert into MakeDim values('FIRNET05.condocerts.dmz','Condo Certs')
insert into MakeDim values('FIRNET08','Doc-Ex')
insert into MakeDim values('FIRNET08','VMS')
insert into MakeDim values('FIRNET09','Cabanc')
insert into MakeDim values('FIRNET09','VMS')
insert into MakeDim values('FIRNET10','Doc-Ex')
insert into MakeDim values('FIRNET12','Condo Certs')
insert into MakeDim values('FIRNET12TST','Condo Certs')
insert into MakeDim values('FIRNETPARK','imageexceptions')
insert into MakeDim values('FIRPRI01','Domain Controller')
insert into MakeDim values('FIRPRI02','Domain Controller')
insert into MakeDim values('FIRPRX01','ISA')
insert into MakeDim values('FIRPRX01','VMS')
insert into MakeDim values('FIRSKL01','Shared SQL Server')
insert into MakeDim values('FIRSKL01','VMS')
insert into MakeDim values('FTNMSG02','Avaya')
insert into MakeDim values('FTNMSG03','Avaya')
insert into MakeDim values('ICS','AFS/VisionIP/CAPI')
insert into MakeDim values('ICS','Image Quality Monitor')
insert into MakeDim values('ICS','VisionIP')
insert into MakeDim values('ICS2','Image Quality Monitor')
insert into MakeDim values('ICS2','Vengine')
insert into MakeDim values('ICS2','VisionIP')
insert into MakeDim values('LX090','Vontu')
insert into MakeDim values('MFA1','TriCipher')
insert into MakeDim values('MFA2','TriCipher')
insert into MakeDim values('MFA3','TriCipher')
insert into MakeDim values('OPSRDS01','Bloomberg')
insert into MakeDim values('OPSRDS01','Radius Server')
insert into MakeDim values('OPSSRC01','Source Code')
insert into MakeDim values('OTGAPP05','SecureZIP')
insert into MakeDim values('OTGAPP05','SQL')
insert into MakeDim values('OTGAPP05','Sunguard')
insert into MakeDim values('OTGAPP05','WS_FTP')
insert into MakeDim values('OTGAPP09','Taskflo')
insert into MakeDim values('OTGAPP09','VisionIP')
insert into MakeDim values('OTGAPP12','SAS')
insert into MakeDim values('OTGAPP13','ActivePerl')
insert into MakeDim values('OTGAPP13','Autoscribe')
insert into MakeDim values('OTGAPP13','dotNet')
insert into MakeDim values('OTGAPP13','FairCom')
insert into MakeDim values('OTGAPP13','Foxtrot')
insert into MakeDim values('OTGAPP13','iSeries Access')
insert into MakeDim values('OTGAPP13','TEDI')
insert into MakeDim values('OTGAPP17','AML  ')
insert into MakeDim values('OTGAPP17','Crystal Reports')
insert into MakeDim values('OTGAPP17','SQL 2005')
insert into MakeDim values('OTGAPP17TST','AML')
insert into MakeDim values('OTGAPP31-NEW','Oracle')
insert into MakeDim values('OTGAPP31-NEW','Sendero /IPS')
insert into MakeDim values('OTGAPP31-NEW','Sendero/IPS')
insert into MakeDim values('OTGARC02','Retention')
insert into MakeDim values('OTGETL01','Data Integrator')
insert into MakeDim values('OTGETL02','Embarcadero')
insert into MakeDim values('OTGFPS01','File Server')
insert into MakeDim values('OTGFSR01','File Server')
insert into MakeDim values('OTGIMG01','Ghost imaging server')
insert into MakeDim values('OTGINET01','Bart')
insert into MakeDim values('OTGINET02','bart')
insert into MakeDim values('OTGMON02','OpManager+F137')
insert into MakeDim values('OTGMON03','SolarWinds')
insert into MakeDim values('OTGMON04','Shavlik')
insert into MakeDim values('OTGMON05','Shavlik')
insert into MakeDim values('OTGMON10','San Monitor')
insert into MakeDim values('OTGMONSQL01','Shared SQL Server')
insert into MakeDim values('OTGOPEX1','AFS')
insert into MakeDim values('OTGOPEX1','APC')
insert into MakeDim values('OTGOPEX1','CertainScan for 7200')
insert into MakeDim values('OTGOPEX1','VisionIP')
insert into MakeDim values('OTGOPEX2','AFS')
insert into MakeDim values('OTGOPEX2','APC')
insert into MakeDim values('OTGOPEX2','CertainScan for 7200')
insert into MakeDim values('OTGOPEX2','VisionIP')
insert into MakeDim values('OTGREP02','Veritas')
insert into MakeDim values('OTGRPT01','Business Objects')
insert into MakeDim values('OTGRPT03','Shared SQL Server')
insert into MakeDim values('OTGSKL08','Shared SQL Server')
insert into MakeDim values('OTGSKL09','Shared SQL Server')
insert into MakeDim values('OTGSQL01','Shared SQL Server')
insert into MakeDim values('OTGSQL01TST','Shared SQL Server')
insert into MakeDim values('OTGSQL03','Shared SQL Server')
insert into MakeDim values('OTGSQL04','Shared SQL Server')
insert into MakeDim values('OTGSQL06','Shared SQL Server')
insert into MakeDim values('OTGSQL07','Shared SQL Server')
insert into MakeDim values('PHXDAFSICU1','AFS')
insert into MakeDim values('PHXDAFSICU1','Image Collation Utility')
insert into MakeDim values('PHXDAFSICU1','VisionIP')
insert into MakeDim values('PHXDAFSICU2','AFS')
insert into MakeDim values('PHXDAFSICU2','Image Collation Utility')
insert into MakeDim values('PHXDAFSICU2','VisionIP')
insert into MakeDim values('PHXDAFSICU3','AFS')
insert into MakeDim values('PHXDAFSICU3','Image Collation Utility')
insert into MakeDim values('PHXDAFSICU3','VisionIP')
insert into MakeDim values('PHXDBAA04','AFS')
insert into MakeDim values('PHXDBAA05','AFS')
insert into MakeDim values('PHXDBAA05','VisionIP')
insert into MakeDim values('PHXDBAA06','AFS')
insert into MakeDim values('PHXDBAA06','Orbograph (OrboTool)')
insert into MakeDim values('PHXDBAA06','VisionIP')
insert into MakeDim values('PHXDBAA10','AFS')
insert into MakeDim values('PHXDBAA11','AFS')
insert into MakeDim values('PHXDBAA12 ','AFS')
insert into MakeDim values('PHXDBAS02','Nacha')
insert into MakeDim values('PHXDBAS03','WinDSX')
insert into MakeDim values('PHXDBAS05','CRAwiz')
insert into MakeDim values('PHXDBAS06','Track-IT Server')
insert into MakeDim values('PHXDBAS07','18 Essbase related services')
insert into MakeDim values('PHXDBAS07','Essbase-Hyperion')
insert into MakeDim values('PHXDBAS07','IIS')
insert into MakeDim values('PHXDBAS08','Essbase-Hyperion')
insert into MakeDim values('PHXDBAS08','Hypservice (for Hyperion Essbase)')
insert into MakeDim values('PHXDBAS08','IIS')
insert into MakeDim values('PHXDBAS09','DSS Server')
insert into MakeDim values('PHXDBAS10','Appworx')
insert into MakeDim values('PHXDBAS10','Voyager')
insert into MakeDim values('PHXDBAS11','Dropbox/Job Server')
insert into MakeDim values('PHXDBAS12','Indata Server')
insert into MakeDim values('PHXDBAS13','PMC IDC Sharepoint Server')
insert into MakeDim values('PHXDBAS14','32-bit ODBC connection to Nautilus DB')
insert into MakeDim values('PHXDBAS14','Lotus Notes')
insert into MakeDim values('PHXDBAS14','Nautilus')
insert into MakeDim values('PHXDBAS14','Prod Nautilus eStatement Notifications/Delivery')
insert into MakeDim values('PHXDBAS15','1stCustomQueryInfo')
insert into MakeDim values('PHXDBAS15','1stDocumentInfo')
insert into MakeDim values('PHXDBAS15','Desktop_FIAPI')
insert into MakeDim values('PHXDBAS15','IIS 7')
insert into MakeDim values('PHXDBAS15','Nautilus')
insert into MakeDim values('PHXDBAS15','Prod Nautilus WebView Processing, Web Services Processing')
insert into MakeDim values('PHXDBAS15','WebViewAdvanced')
insert into MakeDim values('PHXDBAS16','Nautilus')
insert into MakeDim values('PHXDBAS16','Nautilus Thin Client')
insert into MakeDim values('PHXDBAS16','Prod Nautilus Workflow Server DIP Processing')
insert into MakeDim values('PHXDBAS17','Hyland Barcode Recognition')
insert into MakeDim values('PHXDBAS17','Nautilus')
insert into MakeDim values('PHXDBAS18','IIS 7')
insert into MakeDim values('PHXDBAS18','Nautilus')
insert into MakeDim values('PHXDBAS19','IIS 7')
insert into MakeDim values('PHXDBAS19','Nautilus')
insert into MakeDim values('PHXDBAS20','Apache Tomcat')
insert into MakeDim values('PHXDBAS20','DocPlus')
insert into MakeDim values('PHXDBAS20','Fiserv')
insert into MakeDim values('PHXDBAS20','iSeries ')
insert into MakeDim values('PHXDBAS20','Nautilus ')
insert into MakeDim values('PHXDBAS21','DocPlus')
insert into MakeDim values('PHXDBAS21','iSeries')
insert into MakeDim values('PHXDBAS22','BAS20')
insert into MakeDim values('PHXDBAS22','DocPlus')
insert into MakeDim values('PHXDBAS25','Business Objects')
insert into MakeDim values('PHXDBAS26','Tomcat Server (BO) - Prod')
insert into MakeDim values('PHXDBAS27','Eye 360 Analytics')
insert into MakeDim values('PHXDBAS28','dotNet')
insert into MakeDim values('PHXDBCX01','Bloomberg')
insert into MakeDim values('PHXDBCX01','Citrix')
insert into MakeDim values('PHXDBCX02','Bloomberg')
insert into MakeDim values('PHXDBCX02','Citrix')
insert into MakeDim values('PHXDBDB02','SQL Server')
insert into MakeDim values('PHXDBDB04','Symantec')
insert into MakeDim values('PHXDBDB05','Bloomberg')
insert into MakeDim values('PHXDBDB05','VMware Virtual Center')
insert into MakeDim values('PHXDBDB06','Shared SQL Server')
insert into MakeDim values('PHXDBDB09','IIS 7')
insert into MakeDim values('PHXDBDB09','Nautilus')
insert into MakeDim values('PHXDBDB09','SQL ')
insert into MakeDim values('PHXDBDB10','Business Objects')
insert into MakeDim values('PHXDBDB11','Business Objects')
insert into MakeDim values('PHXDBDB12','AppSense')
insert into MakeDim values('PHXDBDM01','Lotus Notes')
insert into MakeDim values('PHXDBDM02','Lotus Notes')
insert into MakeDim values('PHXDBDS01','EskerFax')
insert into MakeDim values('PHXDBDT01','SQL dev/test')
insert into MakeDim values('PHXDBDT02','SQL dev/test')
insert into MakeDim values('PHXDBDT03','SQL dev/test')
insert into MakeDim values('PHXDBDT04','SQL dev/test PMCIDC')
insert into MakeDim values('PHXDBDT05','Business Objects Dev/Test SQL')
insert into MakeDim values('PHXDBDT06','Voyager DEV SQL Server')
insert into MakeDim values('PHXDBDT07','Voyager Relationship Manager')
insert into MakeDim values('PHXDBDT09','SQL test Nautilus, Import Processing, File Server')
insert into MakeDim values('PHXDBDT10','SQL WRG test Nautilus, Import Processing, File Server')
insert into MakeDim values('PHXDBDT11','DEV SQL Server')
insert into MakeDim values('PHXDBFS01','File Server')
insert into MakeDim values('PHXDBFS02','INfoSec')
insert into MakeDim values('PHXDBFS03','SCCM ')
insert into MakeDim values('PHXDBIS01','Bloomberg')
insert into MakeDim values('PHXDBIS01','NTBANK ')
insert into MakeDim values('PHXDBIS02','Bloomberg')
insert into MakeDim values('PHXDBIS02','NTBANK ')
insert into MakeDim values('PHXDBLS01','Citrix')
insert into MakeDim values('PHXDBPK01','NTBANK')
insert into MakeDim values('PHXDBPV01','Citrix')
insert into MakeDim values('PHXDBPV02','Citrix')
insert into MakeDim values('PHXDBSM02','Netvantage')
insert into MakeDim values('PHXDBSM03','Symantec')
insert into MakeDim values('PHXDBSM04','Symantec')
insert into MakeDim values('PHXDBSM05','Avaya ')
insert into MakeDim values('PHXDBSM06','SCCM Servers NTBANK')
insert into MakeDim values('PHXDBSM07','IBM Director')
insert into MakeDim values('PHXDBSM09','TSM')
insert into MakeDim values('PHXDBSM11','Vontu')
insert into MakeDim values('PHXDBSM12','ArcSight')
insert into MakeDim values('PHXDBSM13','Control-M')
insert into MakeDim values('PHXDBSM14','Utimaco Server NTBANK')
insert into MakeDim values('PHXDBSM15','Test Shavlik Server')
insert into MakeDim values('PHXDBSM16','AppSense Sempra')
insert into MakeDim values('PHXDBSM17','SCCM Desktop NTBANK')
insert into MakeDim values('PHXDBSM19','AppSense Sempra ')
insert into MakeDim values('PHXDBSM21','Gold Image')
insert into MakeDim values('PHXDBSM22','Citrix')
insert into MakeDim values('PHXDBSM23','Insight')
insert into MakeDim values('PHXDBSM24','Control M')
insert into MakeDim values('PHXDBSM25','Control M ')
insert into MakeDim values('PHXDBSM26','Symantec')
insert into MakeDim values('PHXDBTS01','AFS')
insert into MakeDim values('PHXDBTS02','Appworx')
insert into MakeDim values('PHXDBTS03','Sharepoint')
insert into MakeDim values('PHXDBTS05','AFS')
insert into MakeDim values('PHXDBTS06','Voyager')
insert into MakeDim values('PHXDBTS07','Voyager')
insert into MakeDim values('PHXDBTS08','Hyperion')
insert into MakeDim values('PHXDBTS09','Hyperion')
insert into MakeDim values('PHXDBTS10','Track-IT')
insert into MakeDim values('PHXDBTS13','OPEX ')
insert into MakeDim values('PHXDBTS15','Nautilus')
insert into MakeDim values('PHXDBTS16','Nautilus ')
insert into MakeDim values('PHXDBTS17','Nautilus')
insert into MakeDim values('PHXDBTS18','Nautilus')
insert into MakeDim values('PHXDBTS19','DocPlus')
insert into MakeDim values('PHXDBTS20','DocPlus')
insert into MakeDim values('PHXDBTS21','DocPlus WRG')
insert into MakeDim values('PHXDBTS22','DocPlus WRG ')
insert into MakeDim values('PHXDBTS25','Business Objects')
insert into MakeDim values('PHXDBTS26','Business Objects')
insert into MakeDim values('PHXDBTS27','Control M')
insert into MakeDim values('PHXDBTS28','Signature')
insert into MakeDim values('PHXDBVC01','VMware Virtual Center')
insert into MakeDim values('PHXDBVC02','VMware Virtual Center')
insert into MakeDim values('PHXDBVC03','VMware Virtual Center ')
insert into MakeDim values('PHXDBVC04','Vmware Virtual Center')
insert into MakeDim values('PHXDBWA01','dotNet')
insert into MakeDim values('PHXDBWA03','PMCIDC')
insert into MakeDim values('PHXDBWA04','Condo Certs')
insert into MakeDim values('PHXDBWA05','InfoSec IIS Reporting Server')
insert into MakeDim values('PHXDBWD01','Web Development Server IIS, applicationmanagement.app, cab.pci.assessment.app, DevWiki, di.conversion.app, node2.test.documentportal.app, node3.test.documentportal.app, test.applicationqueue.app, test.cab.interop.services.onlinepayment.app, test.cab.services.globa')
insert into MakeDim values('PHXDBWD03','DEV PMCIDC IIS')
insert into MakeDim values('PHXDBWD04','Condo Certs')
insert into MakeDim values('PHXDBWD05','Tomcat DEV Server, Test.Services.PaymentProcessor.fnbaonline.com')
insert into MakeDim values('PHXDBXA101','Citrix')
insert into MakeDim values('PHXDBXA102','Citrix')
insert into MakeDim values('PHXDBXA103','Citrix')
insert into MakeDim values('PHXDBXB01','Citrix')
insert into MakeDim values('PHXDBXB02','Citrix')
insert into MakeDim values('PHXDBXD03','Citrix')
insert into MakeDim values('PHXDBXD04','Citrix ')
insert into MakeDim values('PHXDFDB01','Hyperion ')
insert into MakeDim values('PHXDFDB03','E&Y ')
insert into MakeDim values('PHXDFDB04','E&Y')
insert into MakeDim values('PHXDFDT01','ETL')
insert into MakeDim values('PHXDFSM01','PRTG')
insert into MakeDim values('PHXDIIS01','MUOBPCI ')
insert into MakeDim values('PHXDIIS02','MUOBPCI')
insert into MakeDim values('PHXDIPX01','MUOBPCI ')
insert into MakeDim values('PHXDITS02','Cabanc Test Apache Server')
insert into MakeDim values('PHXDITS03','Test Cabanc User Interface')
insert into MakeDim values('PHXDIWE02','cabpayments.mutualofomahabank.com')
insert into MakeDim values('PHXDLX001','LDAP')
insert into MakeDim values('PHXDLX002','LDAP')
insert into MakeDim values('PHXDLX003','Condo Certs')
insert into MakeDim values('PHXDLX005','ArcSight ')
insert into MakeDim values('PHXDLX172','Avaya')
insert into MakeDim values('PHXDVPR01a.virtual.host','VMware Host')
insert into MakeDim values('PHXDVPR01b.virtual.host','VMware Host')
insert into MakeDim values('PHXDVPR01c.virtual.host','VMware Host')
insert into MakeDim values('PHXDVPR01d.virtual.host','VMware Host')
insert into MakeDim values('PHXDVPR01e.virtual.host','VMware Host')
insert into MakeDim values('PHXDVPR01f.virtual.host','VMware Host')
insert into MakeDim values('PHXDVPR01g.virtual.host','VMware Host')
insert into MakeDim values('PHXDVPR01h.virtual.host','VMware Host')
insert into MakeDim values('PHXDVVM01a.virtual.host','VMware Host')
insert into MakeDim values('PHXDVVM01b.virtual.host','VMware Host')
insert into MakeDim values('PHXDVVM01c.virtual.host','VMware Host')
insert into MakeDim values('PHXDVVM01d.virtual.host','VMware Host')
insert into MakeDim values('PHXDX959','Software Repository - NIM')
insert into MakeDim values('PHXDX977','TSM')
insert into MakeDim values('PHXDX9V1','VIO')
insert into MakeDim values('PHXDX9V2','VIO')
insert into MakeDim values('PHXDX9V3','VIO')
insert into MakeDim values('PHXDX9V4','VIO')
insert into MakeDim values('PHXDX9Y0','Condo Certs')
insert into MakeDim values('PHXDX9Y1','Condo Certs')
insert into MakeDim values('PHXDX9Y2','Condo Certs')
insert into MakeDim values('PHXDX9Y8','Control-M')
insert into MakeDim values('PHXDX9Y9','Control-M')
insert into MakeDim values('PHXDZAS01','MutualRoutingNumberWebService')
insert into MakeDim values('PHXDZAS02','MutualRoutingNumberWebService')
insert into MakeDim values('PHXDZAS03','cab.interop.services.onlinepayment.app, cab.services.global.app, cab.services.onlinepayment.app, membership.services.global.app, notifications.services.global.app, services.documentportal.app')
insert into MakeDim values('PHXDZAS03','Doc Portal')
insert into MakeDim values('PHXDZAS04','DMZ SFTP Server')
insert into MakeDim values('PHXDZAS05','IIS 7')
insert into MakeDim values('PHXDZAS05','Voyager')
insert into MakeDim values('PHXDZAS06','IIS 7')
insert into MakeDim values('PHXDZAS06','Voyager')
insert into MakeDim values('PHXDZAS07','BeyondCompare')
insert into MakeDim values('PHXDZAS07','IIS 7')
insert into MakeDim values('PHXDZAS07','SQL')
insert into MakeDim values('PHXDZAS07','UltraEdit')
insert into MakeDim values('PHXDZAS07','Voyager')
insert into MakeDim values('PHXDZAS08','BeyondCompare')
insert into MakeDim values('PHXDZAS08','IIS 7')
insert into MakeDim values('PHXDZAS08','SQL')
insert into MakeDim values('PHXDZAS08','UltraEdit')
insert into MakeDim values('PHXDZAS08','Voyager')
insert into MakeDim values('PHXDZAS09','BeyondCompare')
insert into MakeDim values('PHXDZAS09','IIS 7')
insert into MakeDim values('PHXDZAS09','SQL Server')
insert into MakeDim values('PHXDZAS09','UltraEdit')
insert into MakeDim values('PHXDZAS09','Voyager')
insert into MakeDim values('PHXDZAS10','BeyondCompare')
insert into MakeDim values('PHXDZAS10','IIS 7')
insert into MakeDim values('PHXDZAS10','SQL Server')
insert into MakeDim values('PHXDZAS10','UltraEdit')
insert into MakeDim values('PHXDZAS10','Voyager')
insert into MakeDim values('phxdzdb01','CIV')
insert into MakeDim values('PHXDZDB01','Doc Portal')
insert into MakeDim values('PHXDZDB01','SQL Server')
insert into MakeDim values('PHXDZDB02','Voyager')
insert into MakeDim values('PHXDZDB03','Voyager')
insert into MakeDim values('PHXDZDB04','Voyager')
insert into MakeDim values('PHXDZDB05','Voyager')
insert into MakeDim values('PHXDZSM02','Batch')
insert into MakeDim values('PHXDZWD01','Condo Certs')
insert into MakeDim values('phxdzwe01','CIV')
insert into MakeDim values('PHXDZWE01','wsdl.cagsoftware.com, www.cagsoftware.com, cabimageretrieval.cagsoftware.com, cabimage.cagsoftware.com')
insert into MakeDim values('PHXDZWE02','')
insert into MakeDim values('PHXDZWE04','cabdocs.mutualofomahabank.com, docportal.mutualofomahabank.com, imageeceptions.mutualofomahabank.com, ie.mutualofomahabank.com')
insert into MakeDim values('PHXDZWE04','Doc Portal')
insert into MakeDim values('PHXDZWE12','Condo Certs')
insert into MakeDim values('PMAAPP01','Pima, Nyfix')
insert into MakeDim values('PMAAPP02','Pima, Nyfix')
insert into MakeDim values('PMAESX01.virtual.host','VMware Host')
insert into MakeDim values('PMAESX02.virtual.host','VMware Host')
insert into MakeDim values('PMAFSR01','Pima')
insert into MakeDim values('SASAPP01','SAS')
insert into MakeDim values('SASAPP02','SAS')
insert into MakeDim values('SCU','AFS')
insert into MakeDim values('SCU','CAPI')
insert into MakeDim values('SCU','VisionIP')
insert into MakeDim values('SCU2','AFS')
insert into MakeDim values('SCU2','CAPI')
insert into MakeDim values('SCU2','VisionIP')
insert into MakeDim values('SDLRBIS01','Pima')
insert into MakeDim values('TSTIIS01','Test IIS')
insert into MakeDim values('X967','TSM3')


/* Clean Data */

UPDATE MakeDim SET ServerName = LTRIM(RTRIM(ServerName)), AppName = LTRIM(RTRIM(AppName))


/* Create a cursor to go thru each server */
DECLARE @AppList VARCHAR(5000),@ServerName VARCHAR(50)

DECLARE cSname CURSOR FAST_FORWARD READ_ONLY FOR
SELECT ServerName FROM MakeDim GROUP BY ServerName ORDER BY ServerName

OPEN cSname

FETCH NEXT FROM cSname INTO @ServerName

WHILE @@FETCH_STATUS = 0
BEGIN

SET @AppList = null

/* Create a slash demimited list of apps for the current server */
  SELECT  @AppList = COALESCE(@AppList + '/', '') + AppName
        FROM    MakeDim WHERE ServerName = @ServerName

/* insert list in to output table*/        
        INSERT INTO DimAppList VALUES(@ServerName, @AppList)

FETCH NEXT FROM cSname INTO @ServerName

END

CLOSE cSname
DEALLOCATE cSname

/* Get final List */
SELECT * FROM DimAppList


   